// getAdvantage CLI — GITHUB ACTION WRITER (`getadvantage github-action`,
// alias `init --github-action`).
//
// Writes .github/workflows/getadvantage.yml that consumes the first-party
// Action at the repository root (`uses: BellmeJoe/getadvantage-cli@v1`).
// The Action runs the gate, uploads SARIF, and posts an update-in-place PR
// summary (job-summary fallback when PR write is unavailable).
//
// Idempotent + safe: an existing workflow file is never clobbered without
// --force; re-running over an identical file is a clean no-op. A pre-0.9.0
// generated workflow (inline npx steps) is treated as differing — migrate
// only with an explicit --force after the user inspects the diff.
//
// Node built-ins only. ESM.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { c, cliVersion } from "./util.mjs";

const WORKFLOW_REL = ".github/workflows/getadvantage.yml";
const ACTION_REF = "BellmeJoe/getadvantage-cli@v1";
const SARIF_FILE = "getadvantage.sarif";

// Action majors match primary GitHub code-scanning upload documentation
// (2026-07): checkout@v6, upload-sarif@v4. setup-node@v6 is pinned inside
// action.yml (first-party composite). v7 of checkout/setup-node exists on the
// marketplace; keep v6 until the official SARIF docs migrate (P3 carry).
//
// Permissions (least required for the documented upload + PR summary path):
//   contents: read         — checkout
//   security-events: write — SARIF upload to code scanning
//   actions: read          — required for private-repository workflows (GitHub docs)
//   pull-requests: write   — PR summary comments on same-repo PRs
// Fork PRs typically cannot write comments with GITHUB_TOKEN; the Action falls
// back to the job summary. We never generate pull_request_target.
// Code scanning on private/internal repos also needs GitHub Code Security.

/** Build the workflow YAML for the current product (exported for tests). */
export function workflowContents() {
  return `# getAdvantage — the pre-deploy gate in CI (first-party Action).
#
# One-copy install: uses ${ACTION_REF}
#   • Runs the same gate as local \`getadvantage check\` (GO / NO-GO).
#   • Writes SARIF 2.1 and uploads to GitHub code scanning (even on NO-GO).
#   • Posts a concise PR summary with update-in-place (stable marker); falls
#     back to the job summary when PR write permission is unavailable (forks).
#   • Optional --report when GETADVANTAGE_API_KEY is set (never required for the gate).
# Generated by \`getadvantage github-action\` (CLI ${cliVersion()}).
#
# Tag architecture: floating git tag \`v1\` is the Action API major (independent
# of npm package minor/patch). Pin an exact release with
# \`uses: BellmeJoe/getadvantage-cli@v${cliVersion()}\` if you need bit-for-bit
# reproducibility. npm installs use package versions, not the floating \`v1\` tag.
#
# Honest scope: code scanning alerts appear on public repositories. Private and
# internal repositories need GitHub Code Security enabled for uploads to succeed,
# and this workflow includes actions: read (required for private workflows).
# Not a security guarantee. Does not use the pull-request target event (unsafe for forks).
name: getAdvantage check
on:
  push:
  pull_request:
permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: getAdvantage GO/NO-GO
        uses: ${ACTION_REF}
        env:
          GETADVANTAGE_API_KEY: \${{ secrets.GETADVANTAGE_API_KEY }}
`;
}

/**
 * Detect a prior getadvantage-generated workflow that is not the current
 * first-party Action template (0.8.4 inline npx / older pins).
 */
export function isLegacyGeneratedWorkflow(body) {
  const s = String(body || "");
  if (/uses:\s*BellmeJoe\/getadvantage-cli@/.test(s)) return false;
  return (
    /Generated by `getadvantage github-action`/.test(s) ||
    (/getAdvantage check/.test(s) && /upload-sarif@v\d+/.test(s) && /npx --yes getadvantage@/.test(s))
  );
}

function printNextSteps(opts = {}) {
  console.log("");
  console.log(c.bold("  Next steps"));
  console.log(`     1. (Optional) Add the repo secret ${c.bold("GETADVANTAGE_API_KEY")} (your adv_live_ key):`);
  console.log(c.gray("        GitHub → Settings → Secrets and variables → Actions → New repository secret"));
  console.log(`     2. Commit + push the workflow:`);
  console.log(c.gray(`        git add ${WORKFLOW_REL} && git commit -m "ci: getAdvantage first-party Action"`));
  if (opts.migrated) {
    console.log("");
    console.log(c.yellow("     Migrated from a pre-0.9.0 inline workflow to the first-party Action."));
  }
  console.log("");
  console.log(c.gray(`     Consumer pin: uses: ${ACTION_REF}`));
  console.log(c.gray("     What the job does: checkout → first-party Action (gate + SARIF + PR summary)"));
  console.log(c.gray(`     → upload ${SARIF_FILE} via upload-sarif@v4 (always when written) → fail on NO-GO.`));
  console.log(c.gray("     Not a security guarantee. Private repos need GitHub Code Security + actions: read."));
  console.log(c.gray("     Fork PRs: no secrets; PR comments may fall back to the job summary."));
  console.log(c.gray("     Without GETADVANTAGE_API_KEY the check still gates; --report stays best-effort."));
  console.log(c.gray(`     Exact pin (optional): uses: BellmeJoe/getadvantage-cli@v${cliVersion()}`));
}

/**
 * Write the workflow file. Idempotent: identical file → no-op; different file
 * → refuse without --force (never clobber someone's hand-edited workflow).
 * @param {object} o
 * @param {string} o.cwd     repo root
 * @param {boolean} [o.force] overwrite a differing existing file
 * @returns {number} exit code
 */
export function runGithubAction(o) {
  const cwd = o.cwd;
  const abs = path.join(cwd, ".github", "workflows", "getadvantage.yml");
  const body = workflowContents();

  console.log(c.bold("\n  GitHub Action — first-party gate on every push + PR\n"));

  if (existsSync(abs)) {
    const current = readFileSync(abs, "utf8");
    if (current === body) {
      console.log(c.green(`  ✓ ${WORKFLOW_REL} is already in place and up to date — nothing changed.`));
      printNextSteps();
      return 0;
    }
    if (!o.force) {
      console.error(c.red(`  ✗ ${WORKFLOW_REL} already exists and differs — not overwriting it.`));
      if (isLegacyGeneratedWorkflow(current)) {
        console.error(
          c.yellow(
            "     This looks like a pre-0.9.0 generated workflow (inline npx). Re-run with --force to migrate to the first-party Action after you inspect the diff.",
          ),
        );
      } else {
        console.error(c.gray("     Inspect it first, then re-run with --force to replace it."));
      }
      console.error(c.gray("     Cold install (no existing file) writes the first-party template without --force."));
      return 1;
    }
    console.log(c.yellow(`  ⚠ Overwriting the existing ${WORKFLOW_REL} (--force).`));
    const migrated = isLegacyGeneratedWorkflow(current);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, body, "utf8");
    console.log(c.green(`  ✓ Wrote ${WORKFLOW_REL}`));
    printNextSteps({ migrated });
    return 0;
  }

  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, body, "utf8");
  console.log(c.green(`  ✓ Wrote ${WORKFLOW_REL}`));
  console.log(c.gray(`     One-copy consumer: uses: ${ACTION_REF}`));
  printNextSteps();
  return 0;
}
