// getAdvantage CLI — GITHUB ACTION WRITER (`getadvantage github-action`,
// alias `init --github-action`).
//
// Writes .github/workflows/getadvantage.yml: run the pre-deploy gate on every
// push + pull request, write SARIF for GitHub code scanning, and (opt-in, via
// the repo secret) post the run VERDICT + metadata — never the source code —
// to your getAdvantage account.
//
// Idempotent + safe: an existing workflow file is never clobbered without
// --force; re-running over an identical file is a clean no-op.
//
// Node built-ins only. ESM.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { c, cliVersion } from "./util.mjs";

const WORKFLOW_REL = ".github/workflows/getadvantage.yml";
const SARIF_FILE = "getadvantage.sarif";

// `check --ci --report --sarif …` is the exact command the Action runs:
//   --ci      → non-interactive; tolerates the detached-HEAD checkout; base
//               comparisons default to origin/main / GITHUB_BASE_REF.
//   --report  → opt-in: posts the run verdict + metadata (never source code)
//               using the GETADVANTAGE_API_KEY repo secret. Without the secret
//               the gate still runs — reporting just warns (best-effort).
//   --sarif   → writes SARIF 2.1 for GitHub code scanning (redacted messages).
// fetch-depth: 0 keeps origin/main resolvable for the base comparison.
//
// Exit semantics: the gate step captures exit code with continue-on-error so a
// NO-GO still reaches the upload step (`if: always()`). A final step fails the
// job when the gate was non-zero — NO-GO never becomes a green CI check.
//
// Permissions (least required for the upload path GitHub documents):
//   contents: read        — checkout
//   security-events: write — SARIF upload to code scanning
//   actions: read         — required for private-repository workflows (GitHub docs)
// Code scanning on private/internal repos also needs GitHub Code Security
// entitlement — the workflow does not grant that.
//
// Action majors match current GitHub upload documentation (upload-sarif@v4,
// checkout@v6, setup-node@v6). setup-node keeps node-version explicit and does
// not enable package-manager caching (unnecessary for this gate).
//
// Two things the workflow gets right on purpose:
//   • It INSTALLS dependencies (with --ignore-scripts) before the gate, so the
//     typecheck runs the project's OWN, locally-installed TypeScript compiler.
//   • It PINS the CLI version (getadvantage@<version>) so every run is
//     reproducible instead of silently tracking the latest publish.
const PINNED = `getadvantage@${cliVersion()}`;

/** Build the workflow YAML for the current CLI version (exported for tests). */
export function workflowContents() {
  return `# getAdvantage — the pre-deploy gate in CI.
#
# Runs \`getadvantage check\` on every push + pull request: secret scan, build/
# typecheck, dirty-tree + schema-bump guards -> a plain GO / NO-GO exit code.
# Writes SARIF 2.1 and uploads it to GitHub code scanning so findings show on
# the PR. With GETADVANTAGE_API_KEY set, --report posts the run VERDICT +
# metadata (never your source code) to your getAdvantage account.
# Generated by \`getadvantage github-action\`.
#
# Honest scope: code scanning alerts appear on public repositories. Private and
# internal repositories need GitHub Code Security enabled for uploads to succeed,
# and this workflow includes actions: read (required for private workflows).
name: getAdvantage check
on:
  push:
  pull_request:
permissions:
  contents: read
  security-events: write
  actions: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install dependencies (the typecheck uses your own compiler; the gate never downloads one)
        run: |
          if [ -f package-lock.json ]; then npm ci --ignore-scripts; \\
          elif [ -f package.json ]; then npm install --ignore-scripts; \\
          else echo "No package.json — nothing to install."; fi
      - name: getAdvantage check (GO / NO-GO) + SARIF
        id: gate
        continue-on-error: true
        run: npx --yes ${PINNED} check --ci --report --sarif ${SARIF_FILE}
        env:
          GETADVANTAGE_API_KEY: \${{ secrets.GETADVANTAGE_API_KEY }}
      - name: Upload getAdvantage SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${SARIF_FILE}
          category: getadvantage
      - name: Fail job on NO-GO
        if: steps.gate.outcome == 'failure'
        run: |
          echo "getAdvantage returned NO-GO (or failed). Findings (if any) were uploaded to code scanning."
          exit 1
`;
}

const WORKFLOW = workflowContents();

function printNextSteps() {
  console.log("");
  console.log(c.bold("  Next steps"));
  console.log(`     1. (Optional) Add the repo secret ${c.bold("GETADVANTAGE_API_KEY")} (your adv_live_ key):`);
  console.log(c.gray("        GitHub → Settings → Secrets and variables → Actions → New repository secret"));
  console.log(`     2. Commit + push the workflow:`);
  console.log(c.gray(`        git add ${WORKFLOW_REL} && git commit -m "ci: getAdvantage check + SARIF"`));
  console.log("");
  console.log(c.gray("     What the job does: runs the gate (exit 0 = GO, non-zero = NO-GO), writes"));
  console.log(c.gray(`     ${SARIF_FILE}, uploads it with github/codeql-action/upload-sarif@v4 (even on`));
  console.log(c.gray("     NO-GO via always()), then fails the job if the gate failed. Not a security"));
  console.log(c.gray("     guarantee — same checks as local `getadvantage check`. Private repos need"));
  console.log(c.gray("     GitHub Code Security + this workflow's actions: read for code-scanning uploads."));
  console.log(c.gray("     Without GETADVANTAGE_API_KEY the check still gates; --report stays best-effort."));
}

/**
 * Write the workflow file. Idempotent: identical file → no-op; different file
 * → refuse without --force (never clobber someone's hand-edited workflow).
 * @param {object} o
 * @param {string} o.cwd     repo root
 * @param {boolean} [o.force] overwrite a differing existing file
 * @returns {number} exit code
 */
export function runGithubAction(o) {
  const cwd = o.cwd;
  const abs = path.join(cwd, ".github", "workflows", "getadvantage.yml");
  // Rebuild each call so a process that imported this module before a version
  // change still emits the current pin (tests may re-import).
  const body = workflowContents();

  console.log(c.bold("\n  GitHub Action — the gate on every push + PR\n"));

  if (existsSync(abs)) {
    const current = readFileSync(abs, "utf8");
    if (current === body) {
      console.log(c.green(`  ✓ ${WORKFLOW_REL} is already in place and up to date — nothing changed.`));
      printNextSteps();
      return 0;
    }
    if (!o.force) {
      console.error(c.red(`  ✗ ${WORKFLOW_REL} already exists and differs — not overwriting it.`));
      console.error(c.gray("     Inspect it first, then re-run with --force to replace it."));
      return 1;
    }
    console.log(c.yellow(`  ⚠ Overwriting the existing ${WORKFLOW_REL} (--force).`));
  }

  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, body, "utf8");
  console.log(c.green(`  ✓ Wrote ${WORKFLOW_REL}`));
  console.log(
    c.gray(
      `     It runs \`npx getadvantage check --ci --report --sarif ${SARIF_FILE}\` then uploads SARIF.`,
    ),
  );
  printNextSteps();
  return 0;
}
