// getAdvantage CLI — GITHUB ACTION WRITER (`getadvantage github-action`,
// alias `init --github-action`).
//
// Writes .github/workflows/getadvantage.yml: run the pre-deploy gate on every
// push + pull request, and (opt-in, via the repo secret) post the run VERDICT
// + metadata — never the source code — to your getAdvantage account.
//
// Idempotent + safe: an existing workflow file is never clobbered without
// --force; re-running over an identical file is a clean no-op.
//
// Node built-ins only. ESM.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { c, cliVersion } from "./util.mjs";

const WORKFLOW_REL = ".github/workflows/getadvantage.yml";

// `check --ci --report` is the exact command the Action runs:
//   --ci      → non-interactive; tolerates the detached-HEAD checkout; base
//               comparisons default to origin/main / GITHUB_BASE_REF.
//   --report  → opt-in: posts the run verdict + metadata (never source code)
//               using the GETADVANTAGE_API_KEY repo secret. Without the secret
//               the gate still runs — reporting just warns (best-effort).
// fetch-depth: 0 keeps origin/main resolvable for the base comparison.
//
// Two things the workflow gets right on purpose:
//   • It INSTALLS dependencies (with --ignore-scripts) before the gate, so the
//     typecheck runs the project's OWN, locally-installed TypeScript compiler.
//     Without an install, `tsc` isn't present and the gate would (in older
//     versions) fetch a squatted third-party `tsc` — never do that in CI.
//   • It PINS the CLI version (getadvantage@<version>) so every run is
//     reproducible instead of silently tracking the latest publish.
const PINNED = `getadvantage@${cliVersion()}`;
const WORKFLOW = `# getAdvantage — the pre-deploy gate in CI.
#
# Runs \`getadvantage check\` on every push + pull request: secret scan, build/
# typecheck, dirty-tree + schema-bump guards -> a plain GO / NO-GO exit code.
# With the GETADVANTAGE_API_KEY secret set, --report posts the run VERDICT +
# metadata (never your source code) to your getAdvantage account.
# Generated by \`getadvantage github-action\`.
name: getAdvantage check
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (the typecheck uses your own compiler; the gate never downloads one)
        run: |
          if [ -f package-lock.json ]; then npm ci --ignore-scripts; \\
          elif [ -f package.json ]; then npm install --ignore-scripts; \\
          else echo "No package.json — nothing to install."; fi
      - name: getAdvantage check (GO / NO-GO)
        run: npx --yes ${PINNED} check --ci --report
        env:
          GETADVANTAGE_API_KEY: \${{ secrets.GETADVANTAGE_API_KEY }}
`;

function printNextSteps() {
  console.log("");
  console.log(c.bold("  Next steps"));
  console.log(`     1. Add the repo secret ${c.bold("GETADVANTAGE_API_KEY")} (your adv_live_ key):`);
  console.log(c.gray("        GitHub → Settings → Secrets and variables → Actions → New repository secret"));
  console.log(`     2. Commit + push the workflow:`);
  console.log(c.gray(`        git add ${WORKFLOW_REL} && git commit -m "ci: getAdvantage check"`));
  console.log("");
  console.log(c.gray("     Honest by design: the gate runs entirely inside the CI job. Only with the"));
  console.log(c.gray("     secret set does --report post the run verdict + metadata to your account —"));
  console.log(c.gray("     never your source code. Without the secret the check still gates; reporting"));
  console.log(c.gray("     warns and stays best-effort (the exit code is always the gate verdict)."));
}

/**
 * Write the workflow file. Idempotent: identical file → no-op; different file
 * → refuse without --force (never clobber someone's hand-edited workflow).
 * @param {object} o
 * @param {string} o.cwd     repo root
 * @param {boolean} [o.force] overwrite a differing existing file
 * @returns {number} exit code
 */
export function runGithubAction(o) {
  const cwd = o.cwd;
  const abs = path.join(cwd, ".github", "workflows", "getadvantage.yml");

  console.log(c.bold("\n  GitHub Action — the gate on every push + PR\n"));

  if (existsSync(abs)) {
    const current = readFileSync(abs, "utf8");
    if (current === WORKFLOW) {
      console.log(c.green(`  ✓ ${WORKFLOW_REL} is already in place and up to date — nothing changed.`));
      printNextSteps();
      return 0;
    }
    if (!o.force) {
      console.error(c.red(`  ✗ ${WORKFLOW_REL} already exists and differs — not overwriting it.`));
      console.error(c.gray("     Inspect it first, then re-run with --force to replace it."));
      return 1;
    }
    console.log(c.yellow(`  ⚠ Overwriting the existing ${WORKFLOW_REL} (--force).`));
  }

  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, WORKFLOW, "utf8");
  console.log(c.green(`  ✓ Wrote ${WORKFLOW_REL}`));
  console.log(c.gray("     It runs `npx getadvantage check --ci --report` on push + pull_request."));
  printNextSteps();
  return 0;
}
